apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
type: Opaque
stringData:
  postgresql-postgres-password: sonar123
  sonarqube-username: admin
  sonarqube-password: admin123
  monitoringPasscode: your-strong-passcode


