apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.7.15
    helm:
      values: |
        controller:
          image:
            repository: jenkins/jenkins
            tag: "2.462.3-lts"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          javaOpts: "-Xms1g -Xmx1g"
          serviceType: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            hostName: jenkins.local
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          adminUser: admin
          adminPassword: jenkins123!
          installPlugins:
            - kubernetes:4203.v1dd44f5b_1cf9
            - workflow-aggregator:596.v8c21c963d92d
            - git:5.2.2
            - configuration-as-code:1775.v810dc950b_514
          JCasC:
            defaultConfig: true
            configScripts:
              welcome-message: |
                jenkins:
                  systemMessage: Welcome to Jenkins on EKS!
          securityRealm: |-
            local:
              allowsSignup: false
              users:
               - id: admin
                 password: jenkins123!
          authorizationStrategy: |-
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
        persistence:
          enabled: true
          storageClass: gp2
          size: 20Gi
        serviceAccount:
          create: true
          name: jenkins
        agent:
          enabled: true
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
