apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: v3.1.4
    helm:
      values: |
        admissionController:
          replicas: 2
          resources:
            limits:
              memory: 384Mi
              cpu: 500m
            requests:
              cpu: 100m
              memory: 128Mi
        cleanupController:
          enabled: true
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              cpu: 100m
              memory: 128Mi
        reportsController:
          enabled: true
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              cpu: 100m
              memory: 128Mi
        namespace: kyverno
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
