apiVersion: kyverno.io/v1
kind: PolicyException
metadata:
  name: jenkins-sonarqube-exceptions
  namespace: kyverno
spec:
  exceptions:
  - policyName: require-non-root-user
    ruleNames:
    - check-runAsNonRoot
  - policyName: disallow-privilege-escalation  
    ruleNames:
    - check-allowPrivilegeEscalation
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - StatefulSet
        namespaces:
        - jenkins
        - sonarqube
        - argocd
        names:
        - "jenkins*"
        - "sonarqube*"
        - "*postgresql*"
---
apiVersion: kyverno.io/v1
kind: PolicyException
metadata:
  name: system-exceptions
  namespace: kyverno
spec:
  exceptions:
  - policyName: require-pod-resources
    ruleNames:
    - validate-resources
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - kube-system
        - ingress-nginx
        - crossplane-system
